site_name: polymathic -- the Well
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    #- navigation.expand
    - navigation.tabs
    - search.suggest  # Enables search suggestion
  custom_dir: docs/overrides
  extra_css:
    - css/extra.css
  logo: 'assets/images/Flatiron+Institute_white.png'

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tools: tools.md
  - Benchmarks: benchmarks.md
  - Simulations:
      - Overview: datasets_overview.md
      - acoustic_scattering_maze_2d:
          - description: descriptions/acoustic_scattering_maze_2d.md
          - animations: additional-pages/acoustic_scattering_maze_2d.md
      - active_matter:
          - description: descriptions/active_matter.md
          - animations: additional-pages/active_matter.md
      - convective_envelope_rsg:
          - description: descriptions/convective_envelope_rsg.md
          - animations: additional-pages/convective_envelope_rsg.md
      - euler_multi_quadrants:
          - description: descriptions/euler_quadrants.md
          - animations: additional-pages/euler_quadrants.md
      - gray_scott_reaction_diffusion:
          - description: descriptions/gray_scott_reaction_diffusion.md
          - animations: additional-pages/gray_scott_reaction_diffusion.md
      - helmholtz_staircase:
          - description: descriptions/helmholtz_staircase.md
          - animations: additional-pages/helmholtz_staircase.md
      - MHD:
          - description: descriptions/MHD_256.md
          - animations: additional-pages/MHD_256.md
      - planetswe:
          - description: descriptions/planetswe.md
          - animations: additional-pages/planetswe.md
      - post_neutron_star_merger:
          - description: descriptions/post_neutron_star_merger.md
          - animations: additional-pages/post_neutron_star_merger.md
      - rayleigh_benard:
          - description: descriptions/rayleigh_benard.md
          - animations: additional-pages/rayleigh_benard.md
      - rayleigh_taylor_instability:
          - description: descriptions/rayleigh_taylor_instability.md
          - animations: additional-pages/rayleigh_taylor_instability.md
      - shear_flow:
          - description: descriptions/shear_flow.md
          - animations: additional-pages/shear_flow.md
      - supernova_explosion:
          - description: descriptions/supernova_explosion.md
          - animations: additional-pages/supernova_explosion.md
      - turbulence_gravity_cooling:
          - description: descriptions/turbulence_gravity_cooling.md
          - animations: additional-pages/turbulence_gravity_cooling.md
      - turbulent_radiative_layer_2D:
          - description: descriptions/turbulent_radiative_layer_2D.md
          - animations: additional-pages/turbulent_radiative_layer_2D.md
      - turbulent_radiative_layer_3D:
          - description: descriptions/turbulent_radiative_layer_3D.md
          - animations: additional-pages/turbulent_radiative_layer_3D.md
      - viscoelastic_instability:
          - description: descriptions/viscoelastic_instability.md
          - animations: additional-pages/viscoelastic_instability.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
